spring:
  datasource:
    url: jdbc:mysql://localhost:3306/letterpick
    username: letterpick
    password: letterpickpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
